# Generated by Django 6.0.6 on 2026-07-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='city',
        ),
        migrations.RemoveField(
            model_name='player',
            name='email',
        ),
        migrations.AddField(
            model_name='player',
            name='neighborhood',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='player',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
